# Send prefix
set-option -g prefix C-a
unbind-key C-a
bind-key C-a send-prefix

# Reload config
bind r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded!"

# Enable mouse control (clickable windows, panes, resizable panes)
setw -g mouse on

# Fix copying
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# Switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Shift arrow to switch windows
bind -n S-Left previous-window
bind -n S-Right next-window

# Split panes using | and -
bind-key v split-window -h
bind-key h split-window -v
unbind '"'
unbind %

# Persist color scheme in Vim
set -g default-terminal "screen-256color"